version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-file:./mlruns}
      - MODEL_DIR=models/latest
    volumes:
      - ./:/app
  # Optional local MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.3
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns